export const EMPLOYEES_CONSTANTS = {
    FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
}

export const DETAILS_CONSTANTS = {
    FETCH_DETAILS: 'FETCH_DETAILS',
};
